export const MAX_DEGREE = 360;
export const VIEW_BOX = '0 0 300 300';
export const xCenter = 150;
export const yCenter = 150;
export const radius = 80;
export const sectorHeight = 70;
export const sectorPadding = 7;
export const outerRadius = 107;
export const textRadius = outerRadius + 20;
