export const recordEnToKo: { [key: string]: string } = {
  feedings: '수유',
  infantFormulas: '분유',
  pees: '소변',
  poops: '대변',
  sleeps: '수면',
  pumpingBreasts: '유축',
  babyFoods: '이유식',
  breastFeedings: '유축 수유',
  fevers: '체온',
  hospitals: '병원',
  medications: '투약',
  snacks: '간식',
  milks: '우유',
  plays: '놀이',
  tummytimes: '터미 타임',
  extras: '기타',
};
